language: ruby
script: bundle exec rake test:units

before_install:
  - gem install bundler

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 2.0.0-p648
  - 1.9.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
